### ISSUE TITLE
请问动态数据源，如何配置druid的web-stat-filter和stat-view-servlet？

### ISSUE THREAD

**Issue by ldcsaa** [baomidou/dynamic-datasource#548]
以下配置无效，访问druid后台页面返回404
```
spring.datasource.dynamic:
  primary: master
  strict: true
  lazy: false
  seata: false
  druid:
    max-active: 10
    min-idle: 1
    max-wait: 3000
    initial-size: 3
    keep-alive: true
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    validation-query: SELECT 1
    validation-query-timeout: 1
    filters: stat,wall,slf4j
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    public-key: "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJRhKGNr3IAJcs4+0ys/4zmwUJoBYqAdx6EcyiWIBt7cIFS5QdruakTmGk8XOVPMVz9jOLOvhPfjLzgPgwaKo6UCAwEAAQ=="
    web-stat-filter:
      enabled: true
      session-stat-enable: true
      url-pattern: /*
      exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/__druid/*"
    stat-view-servlet:
      enabled: true
      url-pattern: "/__druid/*"
      login-username: admin
      login-password: 123456
      allow: localhost,127.0.0.1,192.168.*
      reset-enable: false
```
