### ISSUE TITLE
druid

### ISSUE THREAD

**Issue by HenryGyu** [baomidou/dynamic-datasource#558]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.7.12

dynamic-datasource-spring-boot-starter Version(required): 4.1.3

druid Version(optional): 1.2.16

# Describe what happened
```
# 动态数据源增加druid自定义过滤器
spring:
  datasource:
    dynamic:
      druid:
        proxyFilters:
          - sqlLogFilter
```

Expected Result:
3.x版本是有效的，到了4.x版本，该配置无效
