### ISSUE TITLE
您好，关于DruidConfig中publicKey取值为null的疑问

### ISSUE THREAD

**Issue by jnspring-y** [baomidou/dynamic-datasource#598]
您好，我在SpringBoot项目中配置如下参数
```yaml
spring:
  datasource:
    dynamic:
      strict: true
      primary: master
      druid:
        public-key: Yf7CXqjsRNxT43K0tPcapVvLUkOuzWmQGDZFMyShoAdw2IEli956nH8JeBg1
      datasource:
        master:
```
com.baomidou.dynamic.datasource.spring.boot.autoconfigure.druid.DruidConfig 解析不到数据
查看源码发现在方法 toProperties 中没有从传参g取值赋给publicKey导致该值始终为空
```java
 public Properties toProperties(DruidConfig g) {
        Properties properties = new Properties();
        Integer initialSize = this.initialSize == null ? g.getInitialSize() : this.initialSize;
        if (initialSize != null && !initialSize.equals(DEFAULT_INITIAL_SIZE)) {
            properties.setProperty(INITIAL_SIZE, String.valueOf(initialSize));
        }
// 省略
}
```

请问此处是bug还是有其他考虑呢？

谢谢
