### ISSUE TITLE
config.getConnectionProperties()可能出现空指针问题

### ISSUE THREAD

**Issue by qq592304796** [baomidou/dynamic-datasource#604]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.3.10.RELEASE

dynamic-datasource-spring-boot-starter Version(required):4.2.0

druid Version(optional):1.2.20

# Describe what happened
config.getConnectionProperties()可能出现空指针问题
![image](https://github.com/baomidou/dynamic-datasource/assets/26601421/79417c31-631e-4088-bd75-95417c2b5f97)
![image](https://github.com/baomidou/dynamic-datasource/assets/26601421/f2bfeee9-c1e8-405d-913b-a1548b550b2c)

Expected Result:
connectProperties赋值前，进行初始化

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
大概什么样的配置会报错? 举个例子, 我去复现下啊

**Comment by qq592304796** [comment]
> 大概什么样的配置会报错? 举个例子, 我去复现下啊

在配置了spring.datasource.dynamic.datasource.master.druid.public-key的情况下。但是没有配置spring.datasource.dynamic.druid.connection-properties就会出现
```yaml
spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: xxx
          username: xx
          password: xx
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            public-key: xxx

---
# 防止空指针问题
spring:
  datasource:
    dynamic:
      druid:
        # noinspection SpringBootApplicationYaml
        connection-properties: config.decrypt=true

```
